# Generated by Django 5.1.7 on 2025-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_booking_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("hospital care", "Hospital Care"),
                    ("checkup companion", "Checkup Companion"),
                    ("adult care", "Adult Care"),
                    ("baby sitting", "Baby Sitting"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
