# Generated by Django 5.1.7 on 2025-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_servicetype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("hospital_care", "Hospital Care"),
                    ("checkup_companion", "Checkup Companion"),
                    ("adult_care", "Adult Care"),
                    ("baby_sitting", "Baby Sitting"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
