# Generated by Django 5.1.7 on 2025-05-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_booking_lang_booking_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="bank_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="last_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="total_earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
