# Generated by Django 5.1.7 on 2025-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_customuser_user_address_partner_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="medical_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/certificates/"
            ),
        ),
    ]
