# Generated by Django 5.1.7 on 2025-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_fcmtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="partner_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
