# Generated by Django 5.1.7 on 2025-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_alter_fcmtoken_token_alter_fcmtoken_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingextension",
            name="partner_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
