# Generated by Django 5.1.7 on 2025-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_booking_released_at_booking_released_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("released", "Released"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
