# Generated by Django 5.1.7 on 2025-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0021_alter_bookingrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="refund_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
