# Generated by Django 5.1.7 on 2025-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0022_transaction_refund_id_transaction_refund_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
