# Generated by Django 5.1.7 on 2025-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_booking_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingextension",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
