# Generated by Django 5.1.7 on 2025-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_bookingextension_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
