# Generated by Django 5.1.7 on 2025-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_servicetype_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="razorpay_contact_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="razorpay_fund_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
