# Generated by Django 5.1.7 on 2025-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_partner_razorpay_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='experience',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['booking', 'status'], name='booking_request_status_idx'),
        ),
    ]
