# Generated by Django 5.1.7 on 2025-06-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_booking_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='partner',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
