# Generated by Django 5.1.7 on 2025-04-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_servicetype_booking_bookingextension_review_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="authentication.partner",
                    ),
                ),
            ],
            options={
                "unique_together": {("partner", "date", "start_time", "end_time")},
            },
        ),
    ]
