# Generated by Django 5.1.7 on 2025-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_alter_servicetype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="lang",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
