# Generated by Django 5.1.7 on 2025-05-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_remove_partner_last_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="adhar_card_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/adhar_cards/back/"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="adhar_card_front",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/adhar_cards/front/"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="driving_license_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/driving_licenses/back/"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="driving_license_front",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/driving_licenses/front/"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="languages_known",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="secondary_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
