# Generated by Django 5.1.7 on 2025-04-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_alter_totpdevice_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TOTPDevice",
        ),
    ]
