# Generated by Django 5.1.7 on 2025-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_is_active_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="medical_certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
