# Generated by Django 5.1.7 on 2025-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_partnerwallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="scheduled_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
