# Generated by Django 5.1.7 on 2025-04-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_partner_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="experience",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
