# Generated by Django 5.1.7 on 2025-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_totpdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totpdevice",
            name="key",
            field=models.CharField(max_length=170),
        ),
    ]
