# Generated by Django 5.1.7 on 2025-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
